export { default as Logo} from './logo.png'
export { default as girl} from './Image.png'
export {default as misr} from './misr.png'
export {default as turkey} from './turkiy.png'
export {default as baa} from './baa.png'
export {default as yevro} from './yevro.png'
export {default as discount1} from './discount1.png'
export {default as discount2} from './discount2.png'
export {default as discount3} from './discount3.png'
export {default as AboutImage} from './about.png'
export { default as person1} from './person1.png'
export { default as person2} from './person2.png'
export { default as person3} from './person3.png'
export { default as person4} from './person4.png'
export { default as person5} from './person5.png'
export { default as person6} from './person6.png'
export {default as footerImage} from './footerImage.png'
export {default as Phone} from './phone.png'
export {default as face1} from './f.png'
export {default as face2} from './face2.png'
export {default as face3} from './face3.png'
export {default as face4} from './face4.png'
export {default as face5} from './face5.png'
export {default as informationImage} from './infoo.png'
export {default as infoGroup} from './infoGroup.png'
export {default as OkImage} from './okk.png'
export {default as Group1} from './gr1.png'
export {default as Group2} from './gr2.png'
export {default as Group3} from './gr3.png'
export {default as misrImage} from './misrr.png'
export {default as yevroImage} from './yevroImage.png'
export {default as BaaImage} from './baaImage.png'
 export {default as TailandImage} from './tailands.png'